"""Tests for the compound-het HTML report assembler and full pipeline."""

from __future__ import annotations

import matplotlib
matplotlib.use("Agg")

import molamola as mm


def _run_full_pipeline(tmp_path, vcf, exons, clinvar, *, genes=None):
    """Helper: run compound_het_main against the synthetic fixtures."""
    args = [
        
        "--vcf", str(vcf),
        "--reference", "hg38",
        "--canonical-exons", str(exons),
        "--clinvar", str(clinvar),
        "--out", str(tmp_path),
    ]
    if genes:
        for g in genes:
            args += ["--gene", g]
    rc = mm.main(args)
    assert rc == 0
    out_files = list(tmp_path.glob("*.compound_het.report.html"))
    assert len(out_files) == 1
    return out_files[0].read_text()


def test_report_contains_gene_section_for_explicit_gene(
    tmp_path, tiny_phased_vcf, tiny_canonical_exons, tiny_clinvar,
):
    html = _run_full_pipeline(
        tmp_path, tiny_phased_vcf, tiny_canonical_exons, tiny_clinvar,
        genes=["GENE_A"],
    )
    assert 'id="gene-GENE_A"' in html
    assert 'GENE_A' in html
    assert 'GRCh38' in html


def test_report_contains_molamola_banner(
    tmp_path, tiny_phased_vcf, tiny_canonical_exons, tiny_clinvar,
):
    html = _run_full_pipeline(
        tmp_path, tiny_phased_vcf, tiny_canonical_exons, tiny_clinvar,
        genes=["GENE_A"],
    )
    # The header SVG is hand-rolled inline; molamola text appears.
    assert 'svg' in html.lower()
    assert 'molamola' in html


def test_report_embeds_png_as_base64(
    tmp_path, tiny_phased_vcf, tiny_canonical_exons, tiny_clinvar,
):
    """PNG rendered to data URI rather than written as separate file."""
    html = _run_full_pipeline(
        tmp_path, tiny_phased_vcf, tiny_canonical_exons, tiny_clinvar,
        genes=["GENE_A"],
    )
    assert "data:image/png;base64," in html
    # No separate PNG file written.
    assert list(tmp_path.glob("*.png")) == []


def test_report_includes_run_metadata(
    tmp_path, tiny_phased_vcf, tiny_canonical_exons, tiny_clinvar,
):
    html = _run_full_pipeline(
        tmp_path, tiny_phased_vcf, tiny_canonical_exons, tiny_clinvar,
        genes=["GENE_A"],
    )
    assert 'class="meta"' in html
    assert "selection rule" in html
    assert "ClinVar source" in html
    assert "canonical exons source" in html
    # Refusal counters: 1 unphased, 1 non_het, 1 multi_allelic, 5 kept.
    assert "kept = 5" in html
    assert "unphased = 1" in html


def test_report_handles_empty_gene_with_placeholder(
    tmp_path, tiny_phased_vcf, tiny_canonical_exons, tiny_clinvar,
):
    """--gene GENE_C: no variants in window, gets a placeholder section."""
    html = _run_full_pipeline(
        tmp_path, tiny_phased_vcf, tiny_canonical_exons, tiny_clinvar,
        genes=["GENE_A", "GENE_C"],
    )
    assert 'id="gene-GENE_A"' in html
    assert 'id="gene-GENE_C"' in html
    assert "No phased het variants in GENE_C" in html


def test_legend_strings_present_in_rendered_png(
    tmp_path, tiny_phased_vcf, tiny_canonical_exons, tiny_clinvar,
):
    """Legend labels per locked spec (no 'missense' prefix on non-missense)."""
    # We can't read PNG bytes for text; instead verify the renderer
    # produces them by checking the HTML contains the gene panel + legend
    # is generated by render_compound_het_png with no errors.
    html = _run_full_pipeline(
        tmp_path, tiny_phased_vcf, tiny_canonical_exons, tiny_clinvar,
        genes=["GENE_A"],
    )
    # The chip strings in the gene panel header derive from stats:
    assert "trans" in html
    assert "cis" in html


def test_chip_counts_match_gene_a_data(
    tmp_path, tiny_phased_vcf, tiny_canonical_exons, tiny_clinvar,
):
    """GENE_A: 4 variants in window, 3 missense, 2 blocks, 1 trans, 0 cis."""
    html = _run_full_pipeline(
        tmp_path, tiny_phased_vcf, tiny_canonical_exons, tiny_clinvar,
        genes=["GENE_A"],
    )
    assert "3 missense / 4 phased hets" in html
    assert "2 block(s)" in html
    assert "1 trans" in html
    assert "0 cis" in html
