"""Unit tests for the self-contained HTML report (always emitted)."""

from __future__ import annotations

import molamola as mm


def test_html_report_written(tiny_vcf, tmp_path):
    """molamola writes a single self-contained HTML report by default."""
    rc = mm.main(["--vcf", str(tiny_vcf), "--out", str(tmp_path)])
    assert rc == 0
    html = tmp_path / "tiny.report.html"
    assert html.exists()


def test_html_report_embeds_figures_as_data_uris(tiny_vcf, tmp_path):
    """Both figures (and the bundled header logo) are inlined as base64 data URIs."""
    mm.main(["--vcf", str(tiny_vcf), "--out", str(tmp_path)])
    text = (tmp_path / "tiny.report.html").read_text()
    # Circos + genome SV map + header fish PNG = 3 inline data URIs.
    assert text.count("data:image/png;base64,") >= 2


def test_html_report_no_separate_pngs(tiny_vcf, tmp_path):
    """No separate PNG files are written to disk; only the .report.html."""
    mm.main(["--vcf", str(tiny_vcf), "--out", str(tmp_path)])
    pngs = list(tmp_path.glob("*.png"))
    assert pngs == [], f"expected zero PNGs, got {[p.name for p in pngs]}"


def test_html_report_has_required_structural_pieces(tiny_vcf, tmp_path):
    """A few non-negotiable structural / accessibility checks."""
    mm.main(["--vcf", str(tiny_vcf), "--out", str(tmp_path)])
    text = (tmp_path / "tiny.report.html").read_text()
    assert text.startswith("<!DOCTYPE html>")
    assert "<title>molamola" in text
    assert "<meta charset=\"UTF-8\">" in text
    # Two figure sections (circos + genome SV map) are embedded.
    assert 'id="fig-circos"' in text
    assert 'id="fig-svmap"' in text
    # Footer credits molamola.
    assert "generated by" in text
    assert "<code>molamola</code>" in text
    # Run metadata lives in a collapsed <details> at the bottom.
    assert '<details class="meta">' in text
    assert ">run metadata</summary>" in text


def test_html_report_no_event_tables(tiny_vcf, tmp_path):
    """The full BND / non-BND SV tables are intentionally not rendered."""
    mm.main(["--vcf", str(tiny_vcf), "--out", str(tmp_path)])
    text = (tmp_path / "tiny.report.html").read_text()
    assert "<table" not in text
    assert "BND events" not in text
    assert "Non-BND SV events" not in text


def test_html_report_default_out_is_vcf_parent(tiny_vcf, tmp_path):
    """Without `--out`, the report lands next to the input VCF."""
    # Copy the VCF into tmp_path so the parent dir is tmp_path.
    vcf_copy = tmp_path / "sample.sniffles.vcf"
    vcf_copy.write_bytes(tiny_vcf.read_bytes())
    rc = mm.main(["--vcf", str(vcf_copy)])
    assert rc == 0
    assert (tmp_path / "sample.sniffles.report.html").exists()


def test_html_report_escapes_html_specials(tiny_vcf, tmp_path):
    """Sample names with HTML specials should not break the page."""
    mm.main([
        "--vcf", str(tiny_vcf), "--out", str(tmp_path),
        "--sample", "<test>&'\"sample",
    ])
    # The output filename strips the dangerous bits via OS, but the
    # title and chips should escape them rather than embed raw.
    html = next(tmp_path.glob("*.report.html"))
    text = html.read_text()
    assert "&lt;test&gt;" in text
    assert "<test>" not in text
